services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: message_system_db
    restart: unless-stopped
    network_mode: "host"
    environment:
      POSTGRES_DB: message_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./build/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d message_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: message_system_redis
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

  # Golang Application
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    restart: unless-stopped
    network_mode: "host"
    environment:
      # Database Configuration (localhost since using host network)
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: message_system
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_SSL_MODE: disable
      # Redis Configuration (localhost since using host network)
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      # Application Configuration
      APP_PORT: 8080
      APP_ENV: development
      # Webhook Configuration
      WEBHOOK_URL: "https://webhook.site/013ffaf1-9c6a-4821-bfe0-458e6977f30f"
      WEBHOOK_AUTH_KEY: "abc"
      WEBHOOK_TIMEOUT: 30
      # Worker Configuration
      MESSAGE_CRON_DURATION: 120
      MESSAGE_BATCH_NUMBER: 2
      WORKER_COUNT: 2
      WORKER_CHAN_BUFFER: 100
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
